spring:
  application:
    name: weather-service
  cloud:
    openfeign:
      client:
        config:
          weatherFeign:
            url: ${WEATHER_API_URL:https://weatherapi-com.p.rapidapi.com/current.json}
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            defaultRequestHeaders:
              X-RapidAPI-Key: ${RAPID_API_KEY:1b2fb77da9mshe628cd401e2aeeap1a4765jsn5f0441de4c3b}
              X-RapidAPI-Host: 'weatherapi-com.p.rapidapi.com'
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${spring.datasource.username}
    username: ${DATABASE_USER:test_user}
    password: ${DATABASE_PASSWORD:test_pass}
logging:
  level:
    org.zalando.logbook: TRACE
logbook:
  predicate:
    include:
      - path: /api/**
        methods:
          - GET
          - POST
wheather-app:
  location: ${LOCATION:Minsk}
  cron: ${CRON_STRING:0 * * * * *}